options:
  profile:
    # TODO: description
    type: string
    default: production
  cluster_name:
    # TODO: description
    type: string
    default: Test Cluster
  truststore-password:
    type: secret
    description: |
      TODO
  keystore-password:
    type: secret
    description: |
      TODO



      