{
 "title": "Cassandra Overview",
 "description": "Monitoring Cassandra with Prometheus using JXM exporter",
 "tags": [
  "cassandra",
  "charm: cassandra"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "lokids", "label": "Loki datasource", "query": "loki" },
   { "name": "prometheusds", "label": "Prometheus datasource", "query": "prometheus" },
   {
    "name": "juju_application",
    "label": "Juju application",
    "query": {
     "query": "label_values(up{juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\"},juju_application)"
    }
   },
   {
    "name": "juju_model_uuid",
    "label": "Juju model uuid",
    "query": {
     "query": "label_values(up{juju_model=~\"$juju_model\"},juju_model_uuid)"
    }
   },
   { "name": "juju_model", "label": "Juju model", "query": { "query": "label_values(up,juju_model)" } },
   {
    "name": "juju_unit",
    "label": "juju_unit",
    "query": {
     "query": "label_values(up{job=~\"cassandra_.*\"},juju_unit)"
    }
   },
   { "name": "interval", "label": "interval", "query": "30s,1m,5m,1h,6h,1d" }
  ]
 },
 "panels": [
  {
   "title": "Node status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"cassandra.*\"}",
     "legendFormat": "{{juju_unit}}"
    }
   ]
  },
  {
   "title": "JVM Heap usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(jvm_memory_used_bytes{area=\"heap\",juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\"} / jvm_memory_max_bytes{area=\"heap\",juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\"}) * 100",
     "legendFormat": "{{juju_unit}}"
    }
   ]
  },
  {
   "title": "OldGen GC duration",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(jvm_gc_collection_seconds_sum{gc=\"G1 Old Generation\",juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\"}[$interval]) / clamp_min(rate(jvm_gc_collection_seconds_count{gc=\"G1 Old Generation\",juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\"}[$interval]), 1)",
     "legendFormat": "{{juju_unit}}"
    }
   ]
  },
  {
   "title": "Connection timeouts",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(cassandra_connection_totaltimeouts_count{juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\"}[$interval])",
     "legendFormat": "{{juju_unit}}"
    }
   ]
  },
  {
   "title": "Pending compactions",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "cassandra_compaction_pendingtasks{juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\"}",
     "legendFormat": "{{juju_unit}}"
    }
   ]
  },
  {
   "title": "ParNew GC duration",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(jvm_gc_collection_seconds_sum{gc=\"G1 Young Generation\",juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\"}[$interval]) / clamp_min(rate(jvm_gc_collection_seconds_count{gc=\"G1 Young Generation\",juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\"}[$interval]), 1)",
     "legendFormat": "{{juju_unit}}"
    }
   ]
  },
  {
   "title": "ClientWrite avg duration",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cassandra_clientrequest_latency_mean{juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\",type=~\"Write\"} > 0",
     "legendFormat": "{{juju_unit}}"
    }
   ]
  },
  {
   "title": "ClientRead avg duration",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cassandra_clientrequest_latency_mean{juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\",type=~\"Read\"} > 0",
     "legendFormat": "{{juju_unit}}"
    }
   ]
  },
  {
   "title": "Timeout exceptions",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(cassandra_clientrequest_timeouts_count{juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\"}[$interval]))",
     "legendFormat": "{{juju_unit}}"
    }
   ]
  },
  {
   "title": "Unavailable exceptions",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(cassandra_clientrequest_unavailables_count{juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\"}[$interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pending threads",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(cassandra_threadpools_pendingtasks{juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Coordinator level stats (data can be R/W using other nodes)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Writes / sec $juju_unit",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 37 },
   "targets": [
    {
     "expr": "rate(cassandra_clientrequest_latency_count{juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\",type=~\"Write.*\"}[$interval]) > 0",
     "legendFormat": "{{type}}-{{juju_unit}}"
    }
   ]
  },
  {
   "title": "Reads / sec $juju_unit",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 37 },
   "targets": [
    {
     "expr": "rate(cassandra_clientrequest_latency_count{juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\",type=~\"Read.*\"}[$interval]) > 0",
     "legendFormat": "{{type}}-{{juju_unit}}"
    }
   ]
  },
  {
   "title": "Avg write latency $juju_unit",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 44 },
   "targets": [
    {
     "expr": "cassandra_clientrequest_latency_mean{juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\",type=~\"Write.*\"} > 0",
     "legendFormat": "{{type}}-{{juju_unit}}"
    }
   ]
  },
  {
   "title": "Avg read latency $juju_unit",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 44 },
   "targets": [
    {
     "expr": "cassandra_clientrequest_latency_mean{juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\",type=~\"Read.*\"} > 0",
     "legendFormat": "{{type}}-{{juju_unit}}"
    }
   ]
  },
  {
   "title": "95thPercentile write latency $juju_unit",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "cassandra_clientrequest_latency_95thpercentile{instance=\"$instance\",juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\"} > 0",
     "legendFormat": "{{type}}-{{juju_unit}}"
    }
   ]
  },
  {
   "title": "95thPercentile read latency $juju_unit",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 51 },
   "targets": [
    {
     "expr": "cassandra_clientrequest_latency_95thpercentile{juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\",type=~\"Read.*\"} > 0",
     "legendFormat": "{{type}}-{{juju_unit}}"
    }
   ]
  },
  {
   "title": "JVM",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 58 },
   "targets": [
    {}
   ]
  },
  {
   "title": "GC Old count / sec $juju_unit",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "jvm_gc_collection_seconds_count{juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\", gc=~\"G1 Old.*\"}",
     "legendFormat": "{{gc}}-{{juju_unit}}"
    }
   ]
  },
  {
   "title": "GC Young count / sec $juju_unit",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "jvm_gc_collection_seconds_count{juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\", gc=~\"G1 Young.*\"}",
     "legendFormat": "{{gc}}-{{juju_unit}}"
    }
   ]
  },
  {
   "title": "GC Old avg time $juju_unit",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 67 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "jvm_gc_collection_seconds_sum{juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\", gc=~\"G1 Old.*\"}",
     "legendFormat": "{{gc}}-{{juju_unit}}"
    }
   ]
  },
  {
   "title": "GC Young avg time $juju_unit",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 67 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "jvm_gc_collection_seconds_sum{juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\", gc=~\"G1 Young.*\"}",
     "legendFormat": "{{gc}}-{{juju_unit}}"
    }
   ]
  },
  {
   "title": "Heap usage $juju_unit",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "(jvm_memory_used_bytes{area=\"heap\",juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\"})",
     "legendFormat": "{{juju_unit}}"
    }
   ]
  },
  {
   "title": "Non-Heap usage $juju_unit",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{area=\"nonheap\",juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\"}",
     "legendFormat": "{{juju_unit}}"
    }
   ]
  },
  {
   "title": "Open file descriptors $juju_unit",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(process_open_fds{juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\"} / process_max_fds{juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\"}) * 100",
     "legendFormat": "{{juju_unit}}"
    }
   ]
  },
  {
   "title": "Memory Pool CodeHeap used $juju_unit",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 92 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "jvm_memory_pool_used_bytes{juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\", pool=~\"CodeHeap.*\"}",
     "legendFormat": "{{pool}}-{{juju_unit}}"
    }
   ]
  },
  {
   "title": "Memory Pool G1 used $juju_unit",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 108 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "jvm_memory_pool_used_bytes{juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\", pool=~\"G1.*\"}",
     "legendFormat": "{{pool}}-{{juju_unit}}"
    }
   ]
  },
  {
   "title": "Memory Pool CCS used $juju_unit",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 124 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "jvm_memory_pool_used_bytes{juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\", pool=~\"Compressed.*\"}",
     "legendFormat": "{{pool}}-{{juju_unit}}"
    }
   ]
  },
  {
   "title": "Memory Pool Metaspace used $juju_unit",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 140 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "jvm_memory_pool_used_bytes{juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\",pool=~\"Metaspace.*\"}",
     "legendFormat": "{{pool}}-{{juju_unit}}"
    }
   ]
  },
  {
   "title": "Threads count $juju_unit",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 156 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "jvm_threads_current{juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\"}",
     "legendFormat": "{{juju_unit}}"
    }
   ]
  },
  {
   "title": "Disk usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 165 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Top10 tables by size $juju_unit",
   "type": "bargauge",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 166 },
   "targets": [
    {
     "expr": "topk(10, sum by(table) (cassandra_table_live_disk_space_used_bytes_count{juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\"}))",
     "legendFormat": "{{table}}"
    }
   ]
  },
  {
   "title": "Total disk usage $juju_unit",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 166 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "cassandra_columnfamily_totaldiskspaceused{juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\",keyspace=\"\"}",
     "legendFormat": "{{juju_unit}}"
    }
   ]
  },
  {
   "title": "Compaction",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 179 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Top10 SSTables count $juju_unit",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 180 },
   "targets": [
    {
     "expr": "topk by(juju_unit) (10, cassandra_columnfamily_livesstablecount{juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\",keyspace=\"\"})",
     "legendFormat": "{{juju_unit}}"
    }
   ]
  },
  {
   "title": "Pending tasks count $juju_unit",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 180 },
   "targets": [
    {
     "expr": "sum by(juju_unit) (cassandra_compaction_pendingtasks{juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\"})",
     "legendFormat": "{{juju_unit}}"
    }
   ]
  },
  {
   "title": "Completed tasks count $juju_unit",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 180 },
   "targets": [
    {
     "expr": "sum by(juju_unit) (cassandra_compaction_completedtasks{juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\"})",
     "legendFormat": "{{juju_unit}}"
    }
   ]
  },
  {
   "title": "Bytes compacted $juju_unit",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 187 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(cassandra_compaction_bytescompacted{juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\"}[$interval])",
     "legendFormat": "{{juju_unit}}"
    }
   ]
  },
  {
   "title": "Completed compactions $juju_unit",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 187 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(cassandra_compaction_totalcompactionscompleted{juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\"}[$interval])",
     "legendFormat": "{{juju_unit}}"
    }
   ]
  },
  {
   "title": "SSTablesPerRead $juju_unit",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 187 },
   "targets": [
    {
     "expr": "cassandra_columnfamily_sstablesperreadhistogram{juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\",keyspace=\"\"}",
     "legendFormat": "{{juju_unit}}"
    }
   ]
  },
  {
   "title": "Connected clients",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 196 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Client count $juju_unit",
   "type": "stat",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 197 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "changes(cassandra_client_connectednativeclients{juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\"}[$__range])",
     "legendFormat": "{{juju_unit}}"
    }
   ]
  },
  {
   "title": "Hinted handoff",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 204 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Total hints / sec $juju_unit",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 205 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "cassandra_storage_totalhints{juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\"}",
     "legendFormat": "{{juju_unit}}"
    }
   ]
  },
  {
   "title": "Total hints in progress $juju_unit",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 205 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "cassandra_storage_totalhintsinprogress{juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\"}",
     "legendFormat": "{{juju_unit}}"
    }
   ]
  },
  {
   "title": "Bloom filter",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 213 },
   "targets": [
    {}
   ]
  },
  {
   "title": "False positives $juju_unit",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 214 },
   "targets": [
    {
     "expr": "cassandra_columnfamily_bloomfilterfalsepositives{juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\",keyspace=\"\"}",
     "legendFormat": "{{juju_unit}}"
    }
   ]
  },
  {
   "title": "False ratio $juju_unit",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 214 },
   "targets": [
    {
     "expr": "cassandra_columnfamily_bloomfilterfalseratio{juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\",keyspace=\"\"}",
     "legendFormat": "{{juju_unit}}"
    }
   ]
  },
  {
   "title": "Disk usage $juju_unit",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 222 },
   "targets": [
    {
     "expr": "cassandra_columnfamily_bloomfilterdiskspaceused{juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\",keyspace=\"\"}",
     "legendFormat": "{{juju_unit}}"
    }
   ]
  },
  {
   "title": "OffHeap memory used $juju_unit",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 222 },
   "targets": [
    {
     "expr": "cassandra_columnfamily_bloomfilteroffheapmemoryused{juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\",keyspace=\"\"}",
     "legendFormat": "{{juju_unit}}"
    }
   ]
  },
  {
   "title": "Thread pools",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 230 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Completed tasks / sec $juju_unit",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 231 },
   "targets": [
    {
     "expr": "sum by(path, threadpools) (cassandra_threadpools_completedtasks{juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\"} > 0)",
     "legendFormat": "{{path}}-{{threadpools}}"
    }
   ]
  },
  {
   "title": "Pending tasks / sec $juju_unit",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 231 },
   "targets": [
    {
     "expr": "sum(cassandra_threadpools_pendingtasks{juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\"}) by (path, threadpools)",
     "legendFormat": "{{path}}-{{threadpools}}"
    }
   ]
  },
  {
   "title": "Dropped messages / sec $juju_unit",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 241 },
   "targets": [
    {
     "expr": "sum by(juju_unit) (cassandra_droppedmessage_dropped{juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\"})",
     "legendFormat": "{{juju_unit}}"
    }
   ]
  },
  {
   "title": "Active tasks $juju_unit",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 241 },
   "targets": [
    {
     "expr": "sum by(juju_unit) (cassandra_threadpools_activetasks{juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\"})",
     "legendFormat": "{{juju_unit}}"
    }
   ]
  },
  {
   "title": "Total blocked tasks / sec $juju_unit",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 248 },
   "targets": [
    {
     "expr": "sum by(juju_unit) (cassandra_threadpools_totalblockedtasks{juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\"})",
     "legendFormat": "{{juju_unit}}"
    }
   ]
  },
  {
   "title": "Currently blocked tasks $juju_unit",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 248 },
   "targets": [
    {
     "expr": "sum by(juju_unit) (cassandra_threadpools_currentlyblockedtasks{juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\"})",
     "legendFormat": "{{juju_unit}}"
    }
   ]
  },
  {
   "title": "Memtables",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 255 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Top10 memtables by table size $juju_unit",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 256 },
   "targets": [
    {
     "expr": "topk(10, sum by(keyspace) (cassandra_keyspace_memtablelivedatasize{juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\"} > 0))",
     "legendFormat": "{{keyspace}}"
    }
   ]
  },
  {
   "title": "Memtables columns count $instance",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 256 },
   "targets": [
    {
     "expr": "cassandra_columnfamily_memtablecolumnscount{juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\",keyspace=\"\"}",
     "legendFormat": "{{juju_unit}}"
    }
   ]
  },
  {
   "title": "CQL",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 265 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CQL regular statements / sec $juju_unit",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 266 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(cassandra_cql_regularstatementsexecuted{juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\"}[$interval])",
     "legendFormat": "{{juju_unit}}"
    }
   ]
  },
  {
   "title": "CQL prepared statements $juju_unit",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 266 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "cassandra_cql_preparedstatementsexecuted{juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\"}",
     "legendFormat": "{{juju_unit}}"
    }
   ]
  },
  {
   "title": "Snapshots",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 273 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Snapshots size $juju_unit",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 274 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "cassandra_columnfamily_snapshotssize{juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\",keyspace=\"\"}",
     "legendFormat": "{{juju_unit}}"
    }
   ]
  }
 ]
}